name: Deploy via SSH
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executando os comandos remotos via ssh
      uses: appleboy/ssh-action@master
      with:
        host: 34.237.125.57
        username: ec2-user
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/html/testedeploy/
